import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class ProjectsService {
  constructor() {}

  projects = [
    {
      id: 1,
      status: 'Active',
      projectName: 'Loqbox',
      image:
        'https://upload.wikimedia.org/wikipedia/commons/4/48/Outdoors-man-portrait_%28cropped%29.jpg',
      clientName: 'venkat',
      employeeCount: '40',
      startedDate: '20-02-2021',
      Deadline: '30-03-2021',
      empWorking: [
        'venkat',
        'gowri',
        'Manga',
        'Mani',
        'gowri',
        'Manga',
        'Mani',
        'gowri',
        'Manga',
        'Mani',
      ],
    },
    {
      id: 2,
      status: 'Inactive',
      projectName: 'Equifax',
      image:
        'https://upload.wikimedia.org/wikipedia/commons/4/48/Outdoors-man-portrait_%28cropped%29.jpg',
      clientName: 'venkat1',
      employeeCount: '41',
      startedDate: '21-02-2022',
      Deadline: '31-03-2022',
      empWorking: [
        'venkat1',
        'gowri',
        'Manga',
        'Mani',
        'gowri',
        'Manga',
        'Mani',
        'gowri',
        'Manga',
        'Mani',
      ],
    },
    {
      id: 3,
      status: 'Active',
      projectName: 'I9 Forms',
      image:
        'https://upload.wikimedia.org/wikipedia/commons/4/48/Outdoors-man-portrait_%28cropped%29.jpg',
      clientName: 'venkat2',
      employeeCount: '44',
      startedDate: '20-02-2022',
      Deadline: '30-03-2022',
      empWorking: [
        'venkat2',
        'gowri',
        'Manga',
        'Mani',
        'gowri',
        'Manga',
        'Mani',
        'gowri',
        'Manga',
        'Mani',
      ],
    },
    {
      id: 4,
      status: 'Active',
      projectName: 'MMS',
      image:
        'https://upload.wikimedia.org/wikipedia/commons/4/48/Outdoors-man-portrait_%28cropped%29.jpg',
      clientName: 'venkat3',
      employeeCount: '43',
      startedDate: '10-02-2022',
      Deadline: '20-03-2022',
      empWorking: [
        'venkat3',
        'gowri',
        'Manga',
        'Mani',
        'gowri',
        'Manga',
        'Mani',
        'gowri',
        'Manga',
        'Mani',
      ],
    },
    {
      id: 5,
      status: 'Active',
      projectName: 'loqbox',
      image:
        'https://upload.wikimedia.org/wikipedia/commons/4/48/Outdoors-man-portrait_%28cropped%29.jpg',
      clientName: 'venkat4',
      employeeCount: '44',
      startedDate: '23-02-2022',
      Deadline: '15-03-2022',
      empWorking: [
        'venkat4',
        'gowri',
        'Manga',
        'Mani',
        'gowri',
        'Manga',
        'Mani',
        'gowri',
        'Manga',
        'Mani',
      ],
    },
    {
      id: 6,
      status: 'Active',
      projectName: 'Equifax',
      image:
        'https://upload.wikimedia.org/wikipedia/commons/4/48/Outdoors-man-portrait_%28cropped%29.jpg',
      clientName: 'venkat2',
      employeeCount: '44',
      startedDate: '11-02-2022',
      Deadline: '25-03-2022',
      empWorking: [
        'venkat5',
        'gowri',
        'Manga',
        'Mani',
        'gowri',
        'Manga',
        'Mani',
        'gowri',
        'Manga',
        'Mani',
      ],
    },
    {
      id: 7,
      status: 'Active',
      projectName: 'Equifax',
      image:
        'https://upload.wikimedia.org/wikipedia/commons/4/48/Outdoors-man-portrait_%28cropped%29.jpg',
      clientName: 'venka92',
      employeeCount: '49',
      startedDate: '8-02-2022',
      Deadline: '30-03-2022',
      empWorking: [
        'venkat6',
        'gowri',
        'Manga',
        'Mani',
        'gowri',
        'Manga',
        'Mani',
        'gowri',
        'Manga',
        'Mani',
      ],
    },
  ];
}
